# Generated by Django 4.1.5 on 2023-02-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='type',
            new_name='role',
        ),
    ]
