# Generated by Django 4.1.5 on 2023-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_type_baseuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('EXAMINER', 'Examiner'), ('ADMIN', 'Admin')], default='STUDENT', max_length=8),
        ),
    ]
